apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-hello
  template:
    metadata:
      labels:
        app: nodejs-hello
    spec:
      containers:
      - name: nodejs-hello
        image: sotirusama/node-hello:latest
        ports:
        - containerPort: 3000