apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nodejs-hello
  template:
    metadata:
      labels:
        app: nodejs-hello
    spec:
      containers:
      - name: nodejs-hello
        image: sotirusama/node-hello:latest 
        ports:
          - containerPort: 3000
        command: ["sh", "-c"]
        args:
          - |
            echo 'Hello Persistent Storage' > /data/hello.txt && \
            node index.js
        volumeMounts:
          - mountPath: "/data"
            name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: nodejs-pvc